[env:waveshare_touch_lcd_3_49]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = waveshare_esp32_s3_touch_lcd_3_49
framework = arduino

upload_speed = 460800
monitor_speed = 115200

lib_ldf_mode = deep+

build_flags =
  -I.
  -Isrc
  -DLV_CONF_INCLUDE_SIMPLE
  -DCORE_DEBUG_LEVEL=3
