[env:waveshare_touch_lcd_3_49]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = waveshare_esp32_s3_touch_lcd_3_49
framework = arduino

upload_speed = 460800
monitor_speed = 115200

lib_ldf_mode = deep+

build_flags =
  -I.
  -Isrc
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Network/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WiFi/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/WebServer/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/FS/src
  -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/Hash/src
  -DLV_CONF_INCLUDE_SIMPLE
  -DCORE_DEBUG_LEVEL=3
  -DDESKCLOCK_FIRMWARE_VERSION=\"0.1.0-dev\"

[env:audio_test]
extends = env:waveshare_touch_lcd_3_49
build_flags =
  ${env:waveshare_touch_lcd_3_49.build_flags}
  -DAUDIO_TEST_MODE
